auth_enabled: false

# Server settings
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

# Storage backend (local filesystem + boltdb)
storage_config:
  boltdb:
    directory: /loki/index

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  enforce_metric_name: false

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory

ruler:
  alertmanager_url: http://localhost:9093
