auth_enabled: false

server:
  http_listen_port: 3100

storage_config:
  boltdb:
    directory: /loki/index

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

chunk_target_size: 1048576

limits_config:
  enforce_metric_name: false

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory

server:
  http_listen_port: 3100

ruler:
  alertmanager_url: http://localhost:9093
